# Generated by Django 3.1.3 on 2020-11-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='num_repetition',
            field=models.IntegerField(default=1),
        ),
    ]
